services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5434:5432
    env_file:
      - api/.env.test

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - 5000:5000
    env_file:
      - api/.env.test
    depends_on:
      - postgres_db
