services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5434:5432
    env_file:
      - api/.env
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: api
    restart: always
    ports:
      - 5000:5000
    env_file:
      - api/.env
    depends_on:
      - postgres_db
    
  react_app:
    build: ./frontend
    container_name: react_app
    restart: always
    env_file:
      - frontend/.env
    depends_on:
      - api
    volumes:
      - react_volume:/var/www/html
    
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - react_app
    volumes:
      - react_volume:/var/www/html

volumes:
  postgres_volume:
  react_volume: